//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DJTUStudentSystem.DataBaseModel
{

	/// <summary>
	/// 实体类VIEW1 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("VIEW1")]
	[Serializable]
	public partial class VIEW1 : Entity 
	{
		#region Model
		private string _学号;
		private string _学生姓名;
		private string _课程名称;
		private string _成绩;
		private int? _ATYID;
		private int? _GradeID;
		private string _Source;
		/// <summary>
		/// 
		/// </summary>
		public string 学号
		{
			get{ return _学号; }
			set
			{
				this.OnPropertyValueChange(_.学号,_学号,value);
				this._学号=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 学生姓名
		{
			get{ return _学生姓名; }
			set
			{
				this.OnPropertyValueChange(_.学生姓名,_学生姓名,value);
				this._学生姓名=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 课程名称
		{
			get{ return _课程名称; }
			set
			{
				this.OnPropertyValueChange(_.课程名称,_课程名称,value);
				this._课程名称=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 成绩
		{
			get{ return _成绩; }
			set
			{
				this.OnPropertyValueChange(_.成绩,_成绩,value);
				this._成绩=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ATYID
		{
			get{ return _ATYID; }
			set
			{
				this.OnPropertyValueChange(_.ATYID,_ATYID,value);
				this._ATYID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? GradeID
		{
			get{ return _GradeID; }
			set
			{
				this.OnPropertyValueChange(_.GradeID,_GradeID,value);
				this._GradeID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.学号,
				_.学生姓名,
				_.课程名称,
				_.成绩,
				_.ATYID,
				_.GradeID,
				_.Source};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._学号,
				this._学生姓名,
				this._课程名称,
				this._成绩,
				this._ATYID,
				this._GradeID,
				this._Source};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","VIEW1");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学号 = new Field("学号","VIEW1","学号");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学生姓名 = new Field("学生姓名","VIEW1","学生姓名");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 课程名称 = new Field("课程名称","VIEW1","课程名称");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 成绩 = new Field("成绩","VIEW1","成绩");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ATYID = new Field("ATYID","VIEW1","ATYID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GradeID = new Field("GradeID","VIEW1","GradeID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Source = new Field("Source","VIEW1","Source");
		}
		#endregion


	}
}

