//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DJTUStudentSystem.DataBaseModel
{

	/// <summary>
	/// 实体类VIEW6 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("VIEW6")]
	[Serializable]
	public partial class VIEW6 : Entity 
	{
		#region Model
		private int? _Expr1;
		private string _学生姓名;
		private string _学号;
		/// <summary>
		/// 
		/// </summary>
		public int? Expr1
		{
			get{ return _Expr1; }
			set
			{
				this.OnPropertyValueChange(_.Expr1,_Expr1,value);
				this._Expr1=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 学生姓名
		{
			get{ return _学生姓名; }
			set
			{
				this.OnPropertyValueChange(_.学生姓名,_学生姓名,value);
				this._学生姓名=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string 学号
		{
			get{ return _学号; }
			set
			{
				this.OnPropertyValueChange(_.学号,_学号,value);
				this._学号=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Expr1,
				_.学生姓名,
				_.学号};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Expr1,
				this._学生姓名,
				this._学号};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","VIEW6");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Expr1 = new Field("Expr1","VIEW6","Expr1");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学生姓名 = new Field("学生姓名","VIEW6","学生姓名");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field 学号 = new Field("学号","VIEW6","学号");
		}
		#endregion


	}
}

