//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DJTUStudentSystem.DataBaseModel
{

	/// <summary>
	/// 实体类VIEW3 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("VIEW3")]
	[Serializable]
	public partial class VIEW3 : Entity 
	{
		#region Model
		private int _Stdid;
		private int? _Dayofweek;
		private decimal? _Expr1;
		private string _Sectionth;
		private string _StdCode;
		private string _StdName;
		/// <summary>
		/// 
		/// </summary>
		public int Stdid
		{
			get{ return _Stdid; }
			set
			{
				this.OnPropertyValueChange(_.Stdid,_Stdid,value);
				this._Stdid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Dayofweek
		{
			get{ return _Dayofweek; }
			set
			{
				this.OnPropertyValueChange(_.Dayofweek,_Dayofweek,value);
				this._Dayofweek=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Expr1
		{
			get{ return _Expr1; }
			set
			{
				this.OnPropertyValueChange(_.Expr1,_Expr1,value);
				this._Expr1=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Sectionth
		{
			get{ return _Sectionth; }
			set
			{
				this.OnPropertyValueChange(_.Sectionth,_Sectionth,value);
				this._Sectionth=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StdCode
		{
			get{ return _StdCode; }
			set
			{
				this.OnPropertyValueChange(_.StdCode,_StdCode,value);
				this._StdCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StdName
		{
			get{ return _StdName; }
			set
			{
				this.OnPropertyValueChange(_.StdName,_StdName,value);
				this._StdName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Stdid,
				_.Dayofweek,
				_.Expr1,
				_.Sectionth,
				_.StdCode,
				_.StdName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Stdid,
				this._Dayofweek,
				this._Expr1,
				this._Sectionth,
				this._StdCode,
				this._StdName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","VIEW3");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stdid = new Field("stdid","VIEW3","stdid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Dayofweek = new Field("dayofweek","VIEW3","dayofweek");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Expr1 = new Field("Expr1","VIEW3","Expr1");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sectionth = new Field("Sectionth","VIEW3","Sectionth");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdCode = new Field("StdCode","VIEW3","StdCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdName = new Field("StdName","VIEW3","StdName");
		}
		#endregion


	}
}

