//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DJTUStudentSystem.DataBaseModel
{

	/// <summary>
	/// 实体类Vw_ChatRoom 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_ChatRoom")]
	[Serializable]
	public partial class Vw_ChatRoom : Entity 
	{
		#region Model
		private string _CMname;
		private DateTime? _CMdate;
		private int _CMID;
		private string _Username;
		private int _CRID;
		private string _State;
		/// <summary>
		/// 
		/// </summary>
		public string CMname
		{
			get{ return _CMname; }
			set
			{
				this.OnPropertyValueChange(_.CMname,_CMname,value);
				this._CMname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CMdate
		{
			get{ return _CMdate; }
			set
			{
				this.OnPropertyValueChange(_.CMdate,_CMdate,value);
				this._CMdate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int CMID
		{
			get{ return _CMID; }
			set
			{
				this.OnPropertyValueChange(_.CMID,_CMID,value);
				this._CMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Username
		{
			get{ return _Username; }
			set
			{
				this.OnPropertyValueChange(_.Username,_Username,value);
				this._Username=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int CRID
		{
			get{ return _CRID; }
			set
			{
				this.OnPropertyValueChange(_.CRID,_CRID,value);
				this._CRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CMname,
				_.CMdate,
				_.CMID,
				_.Username,
				_.CRID,
				_.State};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CMname,
				this._CMdate,
				this._CMID,
				this._Username,
				this._CRID,
				this._State};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_ChatRoom");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMname = new Field("CMname","vw_ChatRoom","CMname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMdate = new Field("CMdate","vw_ChatRoom","CMdate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CMID = new Field("CMID","vw_ChatRoom","CMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Username = new Field("Username","vw_ChatRoom","Username");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CRID = new Field("CRID","vw_ChatRoom","CRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("state","vw_ChatRoom","state");
		}
		#endregion


	}
}

