//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DJTUStudentSystem.DataBaseModel
{

	/// <summary>
	/// 实体类Vw_elitist 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_elitist")]
	[Serializable]
	public partial class Vw_elitist : Entity 
	{
		#region Model
		private string _StdCode;
		private string _StdName;
		private string _DeptName;
		private string _GRName;
		private int _ELID;
		private int? _TMID;
		private int? _Deptid;
		private int? _GRID;
		private int? _Stdid;
		private int? _M90;
		private int? _M80;
		private decimal? _Amount;
		private int? _CNums;
		private int? _M70;
		private int? _M60;
		private int? _MBad;
		/// <summary>
		/// 
		/// </summary>
		public string StdCode
		{
			get{ return _StdCode; }
			set
			{
				this.OnPropertyValueChange(_.StdCode,_StdCode,value);
				this._StdCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StdName
		{
			get{ return _StdName; }
			set
			{
				this.OnPropertyValueChange(_.StdName,_StdName,value);
				this._StdName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DeptName
		{
			get{ return _DeptName; }
			set
			{
				this.OnPropertyValueChange(_.DeptName,_DeptName,value);
				this._DeptName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string GRName
		{
			get{ return _GRName; }
			set
			{
				this.OnPropertyValueChange(_.GRName,_GRName,value);
				this._GRName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ELID
		{
			get{ return _ELID; }
			set
			{
				this.OnPropertyValueChange(_.ELID,_ELID,value);
				this._ELID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? TMID
		{
			get{ return _TMID; }
			set
			{
				this.OnPropertyValueChange(_.TMID,_TMID,value);
				this._TMID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Deptid
		{
			get{ return _Deptid; }
			set
			{
				this.OnPropertyValueChange(_.Deptid,_Deptid,value);
				this._Deptid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? GRID
		{
			get{ return _GRID; }
			set
			{
				this.OnPropertyValueChange(_.GRID,_GRID,value);
				this._GRID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Stdid
		{
			get{ return _Stdid; }
			set
			{
				this.OnPropertyValueChange(_.Stdid,_Stdid,value);
				this._Stdid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? M90
		{
			get{ return _M90; }
			set
			{
				this.OnPropertyValueChange(_.M90,_M90,value);
				this._M90=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? M80
		{
			get{ return _M80; }
			set
			{
				this.OnPropertyValueChange(_.M80,_M80,value);
				this._M80=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Amount
		{
			get{ return _Amount; }
			set
			{
				this.OnPropertyValueChange(_.Amount,_Amount,value);
				this._Amount=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CNums
		{
			get{ return _CNums; }
			set
			{
				this.OnPropertyValueChange(_.CNums,_CNums,value);
				this._CNums=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? M70
		{
			get{ return _M70; }
			set
			{
				this.OnPropertyValueChange(_.M70,_M70,value);
				this._M70=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? M60
		{
			get{ return _M60; }
			set
			{
				this.OnPropertyValueChange(_.M60,_M60,value);
				this._M60=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? MBad
		{
			get{ return _MBad; }
			set
			{
				this.OnPropertyValueChange(_.MBad,_MBad,value);
				this._MBad=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.StdCode,
				_.StdName,
				_.DeptName,
				_.GRName,
				_.ELID,
				_.TMID,
				_.Deptid,
				_.GRID,
				_.Stdid,
				_.M90,
				_.M80,
				_.Amount,
				_.CNums,
				_.M70,
				_.M60,
				_.MBad};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._StdCode,
				this._StdName,
				this._DeptName,
				this._GRName,
				this._ELID,
				this._TMID,
				this._Deptid,
				this._GRID,
				this._Stdid,
				this._M90,
				this._M80,
				this._Amount,
				this._CNums,
				this._M70,
				this._M60,
				this._MBad};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_elitist");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdCode = new Field("StdCode","vw_elitist","StdCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdName = new Field("StdName","vw_elitist","StdName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptName = new Field("DeptName","vw_elitist","DeptName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GRName = new Field("GRName","vw_elitist","GRName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ELID = new Field("ELID","vw_elitist","ELID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TMID = new Field("TMID","vw_elitist","TMID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Deptid = new Field("deptid","vw_elitist","deptid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GRID = new Field("GRID","vw_elitist","GRID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stdid = new Field("stdid","vw_elitist","stdid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field M90 = new Field("M90","vw_elitist","M90");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field M80 = new Field("M80","vw_elitist","M80");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Amount = new Field("Amount","vw_elitist","Amount");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CNums = new Field("CNums","vw_elitist","CNums");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field M70 = new Field("M70","vw_elitist","M70");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field M60 = new Field("M60","vw_elitist","M60");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MBad = new Field("MBad","vw_elitist","MBad");
		}
		#endregion


	}
}

