//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DJTUStudentSystem.DataBaseModel
{

	/// <summary>
	/// 实体类Vw_Stulev 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("vw_Stulev")]
	[Serializable]
	public partial class Vw_Stulev : Entity 
	{
		#region Model
		private string _CCode;
		private string _CCname;
		private string _StdName;
		private string _StdCode;
		private string _Lev;
		private int? _Ccid;
		private int? _Stdid;
		private int? _Atyid;
		private int _STLID;
		private string _ClassName;
		/// <summary>
		/// 
		/// </summary>
		public string CCode
		{
			get{ return _CCode; }
			set
			{
				this.OnPropertyValueChange(_.CCode,_CCode,value);
				this._CCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CCname
		{
			get{ return _CCname; }
			set
			{
				this.OnPropertyValueChange(_.CCname,_CCname,value);
				this._CCname=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StdName
		{
			get{ return _StdName; }
			set
			{
				this.OnPropertyValueChange(_.StdName,_StdName,value);
				this._StdName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StdCode
		{
			get{ return _StdCode; }
			set
			{
				this.OnPropertyValueChange(_.StdCode,_StdCode,value);
				this._StdCode=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Lev
		{
			get{ return _Lev; }
			set
			{
				this.OnPropertyValueChange(_.Lev,_Lev,value);
				this._Lev=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Ccid
		{
			get{ return _Ccid; }
			set
			{
				this.OnPropertyValueChange(_.Ccid,_Ccid,value);
				this._Ccid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Stdid
		{
			get{ return _Stdid; }
			set
			{
				this.OnPropertyValueChange(_.Stdid,_Stdid,value);
				this._Stdid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Atyid
		{
			get{ return _Atyid; }
			set
			{
				this.OnPropertyValueChange(_.Atyid,_Atyid,value);
				this._Atyid=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int STLID
		{
			get{ return _STLID; }
			set
			{
				this.OnPropertyValueChange(_.STLID,_STLID,value);
				this._STLID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ClassName
		{
			get{ return _ClassName; }
			set
			{
				this.OnPropertyValueChange(_.ClassName,_ClassName,value);
				this._ClassName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CCode,
				_.CCname,
				_.StdName,
				_.StdCode,
				_.Lev,
				_.Ccid,
				_.Stdid,
				_.Atyid,
				_.STLID,
				_.ClassName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CCode,
				this._CCname,
				this._StdName,
				this._StdCode,
				this._Lev,
				this._Ccid,
				this._Stdid,
				this._Atyid,
				this._STLID,
				this._ClassName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","vw_Stulev");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCode = new Field("CCode","vw_Stulev","CCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CCname = new Field("CCname","vw_Stulev","CCname");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdName = new Field("StdName","vw_Stulev","StdName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StdCode = new Field("StdCode","vw_Stulev","StdCode");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Lev = new Field("Lev","vw_Stulev","Lev");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Ccid = new Field("ccid","vw_Stulev","ccid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Stdid = new Field("stdid","vw_Stulev","stdid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Atyid = new Field("atyid","vw_Stulev","atyid");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field STLID = new Field("STLID","vw_Stulev","STLID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ClassName = new Field("ClassName","vw_Stulev","ClassName");
		}
		#endregion


	}
}

